<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { listTemplates } from '../api/templates'
import { exportReports } from '../api/reports'
import { getTaskOverview, listTasks, type TaskOverview } from '../api/tasks'
import type { ReportTask, Template } from '../types'

const overview = ref<TaskOverview | null>(null); const tasks = ref<ReportTask[]>([]); const templates = ref<Template[]>([]); const templateId = ref(''); const taskId = ref(''); const loading = ref(false); const error = ref('')
async function load() { loading.value = true; try { [overview.value, tasks.value, templates.value] = await Promise.all([getTaskOverview(), listTasks(), listTemplates()]); if (!templateId.value && templates.value.length) templateId.value = String(templates.value[0].id) } catch (e) { error.value = e instanceof Error ? e.message : '加载失败' } finally { loading.value = false } }
async function download() { if (!templateId.value) return; try { await exportReports(templateId.value, taskId.value || undefined) } catch (e) { error.value = e instanceof Error ? e.message : '导出失败' } }
onMounted(load)
</script>

<template><section><div class="page-heading"><div><h1>数据看板</h1><p>查看任务完成情况，并按模板或任务导出填报数据。</p></div><button class="secondary" @click="load">刷新</button></div><div v-if="error" class="notice error">{{ error }}</div><div v-if="overview" class="form-grid"><div class="editor"><h2>全部任务</h2><strong>{{ overview.total }}</strong></div><div class="editor"><h2>已发布</h2><strong>{{ overview.published }}</strong></div><div class="editor"><h2>即将截止 / 逾期</h2><strong>{{ overview.dueSoon }} / {{ overview.overdue }}</strong></div><div class="editor"><h2>待填人员</h2><strong>{{ overview.pendingAssignees }}</strong></div></div><div class="editor"><h2>导出数据</h2><div class="filters"><select v-model="templateId"><option v-for="item in templates" :key="item.id" :value="String(item.id)">{{ item.name }}</option></select><select v-model="taskId"><option value="">全部任务</option><option v-for="task in tasks.filter(item => String(item.templateId) === templateId)" :key="task.id" :value="String(task.id)">{{ task.name }}{{ task.periodLabel ? ` / ${task.periodLabel}` : '' }}</option></select><button class="primary" @click="download">导出 Excel</button></div></div><div class="table-wrap"><table><thead><tr><th>任务</th><th>模板</th><th>填报人员</th><th>完成进度</th><th>截止时间</th><th>状态</th></tr></thead><tbody><tr v-if="loading"><td colspan="6" class="muted">加载中...</td></tr><tr v-else-if="!tasks.length"><td colspan="6" class="muted">暂无任务。</td></tr><tr v-for="task in tasks" :key="task.id"><td>{{ task.name }}</td><td>{{ task.templateName }}</td><td>{{ task.assignees?.length || 0 }}</td><td>{{ task.progress ? `${task.progress.submittedAssigneeCount} 已提交 / ${task.progress.pendingAssigneeCount} 待填` : '-' }}</td><td>{{ task.deadline?.replace('T',' ') || '-' }}</td><td>{{ task.status }}</td></tr></tbody></table></div></section></template>
