<script setup lang="ts">
import { onMounted, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import { listTasks } from '../api/tasks'
import { approveLateFillRequest, createLateFillRequest, listLateFillLeaders, listLateFillRequests, rejectLateFillRequest, type LateFillRequest } from '../api/lateFill'
import { useAuthStore } from '../stores/auth'
const auth=useAuthStore(),route=useRoute(),requests=ref<LateFillRequest[]>([]),tasks=ref<any[]>([]),leaders=ref<any[]>([]),taskId=ref(String(route.query.taskId||'')),leaderId=ref(''),reason=ref(''),error=ref(''),message=ref('')
const text=(e:unknown)=>e instanceof Error?e.message:'操作失败'
async function load(){try{[requests.value,tasks.value]=await Promise.all([listLateFillRequests(),listTasks()]);if(taskId.value) await loadLeaders()}catch(e){error.value=text(e)}}
async function loadLeaders(){if(!taskId.value)return;try{leaders.value=await listLateFillLeaders(taskId.value);leaderId.value=''}catch(e){error.value=text(e)}}
async function apply(){if(!taskId.value||!leaderId.value||!reason.value.trim()){error.value='请选择逾期任务、指定领导并填写原因';return}try{await createLateFillRequest({taskId:taskId.value,leaderId:leaderId.value,reason:reason.value.trim()});message.value='补报申请已提交';reason.value='';await load()}catch(e){error.value=text(e)}}
async function approve(x:LateFillRequest){const deadline=window.prompt('请输入补报截止时间（YYYY-MM-DDTHH:mm）');if(!deadline)return;try{await approveLateFillRequest(x.id,deadline,window.prompt('审批意见')||'');message.value='已批准补报';await load()}catch(e){error.value=text(e)}}
async function reject(x:LateFillRequest){const comment=window.prompt('请输入驳回原因');if(!comment)return;try{await rejectLateFillRequest(x.id,comment);message.value='已驳回';await load()}catch(e){error.value=text(e)}}
watch(taskId,loadLeaders);onMounted(load)
</script>
<template><section><div class="page-heading"><div><h1>补报申请</h1><p>补报须指定领导审批，并在批准的截止时间前完成。</p></div><button class="secondary" @click="load">刷新</button></div><div v-if="message" class="notice success">{{message}}</div><div v-if="error" class="notice error">{{error}}</div><form v-if="auth.hasRole('REPORTER')" class="editor" @submit.prevent="apply"><label>逾期任务<select v-model="taskId"><option value="">请选择任务</option><option v-for="t in tasks.filter((x:any)=>x.status==='PUBLISHED'&&x.deadline&&new Date(x.deadline)<new Date())" :key="t.id" :value="String(t.id)">{{t.name}}</option></select></label><label>指定领导<select v-model="leaderId"><option value="">请选择领导</option><option v-for="x in leaders" :key="x.id" :value="String(x.id)">{{x.username}}</option></select></label><label>补报原因<textarea v-model.trim="reason" maxlength="500" /></label><button class="primary">提交申请</button></form><div class="table-wrap"><table><thead><tr><th>任务</th><th>申请人</th><th>指定领导</th><th>原因</th><th>状态</th><th>补报截止</th><th>操作</th></tr></thead><tbody><tr v-if="!requests.length"><td colspan="7" class="muted">暂无补报申请。</td></tr><tr v-for="x in requests" :key="x.id"><td>{{x.taskName}}</td><td>{{x.requesterName}}</td><td>{{x.leaderName}}</td><td>{{x.reason}}</td><td>{{x.status}}</td><td>{{x.lateDeadline?.replace('T',' ')||'-'}}</td><td><template v-if="(auth.hasRole('LEADER')||auth.hasRole('ADMIN'))&&x.status==='PENDING'"><button class="text-button" @click="approve(x)">批准</button><button class="danger-button" @click="reject(x)">驳回</button></template><span v-else>-</span></td></tr></tbody></table></div></section></template>
