<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { confirmTemplateImport, createTemplate, deleteTemplate, downloadTemplate, downloadTemplateImportSample, listTemplates, previewTemplateImport, updateTemplate, uploadTemplateFile, type TemplateSheetPreview } from '../api/templates'
import type { Template, TemplateColumn } from '../types'

type FieldRow = Required<Pick<TemplateColumn, 'key' | 'label' | 'type' | 'required' | 'uniqueValue' | 'searchable' | 'aggregatable' | 'listVisible' | 'frozen' | 'importable'>> & Omit<TemplateColumn, 'key' | 'label' | 'type' | 'required' | 'uniqueValue' | 'searchable' | 'aggregatable' | 'listVisible' | 'frozen' | 'importable'> & { optionsText: string }
const templates = ref<Template[]>([]); const loading = ref(false); const message = ref(''); const error = ref(''); const editing = ref<Template | null>(null); const showEditor = ref(false)
const form = ref({ name: '', description: '', status: 'PUBLISHED', columns: [] as FieldRow[] })
const importFile = ref<File | null>(null); const importSheets = ref<Array<TemplateSheetPreview & { templateName: string }>>([]); const importing = ref(false)
function toMessage(e: unknown) { return e instanceof Error ? e.message : '操作失败' }
async function load() { loading.value = true; try { templates.value = await listTemplates() } catch (e) { error.value = toMessage(e) } finally { loading.value = false } }
function nextKey() { return `field_${Date.now()}_${form.value.columns.length + 1}` }
function emptyField(): FieldRow { return { key: nextKey(), label: '', type: 'text', required: false, defaultValue: '', maxLength: undefined, minValue: undefined, maxValue: undefined, scale: undefined, pattern: '', options: [], optionsText: '', uniqueValue: false, searchable: false, aggregatable: false, listVisible: true, frozen: false, importable: true } }
function normalize(column: TemplateColumn): FieldRow { return { ...emptyField(), ...column, type: column.type || 'text', required: Boolean(column.required), uniqueValue: Boolean(column.uniqueValue), searchable: Boolean(column.searchable), aggregatable: Boolean(column.aggregatable), listVisible: column.listVisible !== false, frozen: Boolean(column.frozen), importable: column.importable !== false, optionsText: (column.options || []).join(', ') } }
function openCreate() { showEditor.value = true; editing.value = null; form.value = { name: '', description: '', status: 'PUBLISHED', columns: [emptyField()] } }
function openEdit(item: Template) { showEditor.value = true; editing.value = item; form.value = { name: item.name, description: item.description || '', status: item.status || 'PUBLISHED', columns: (item.columns || []).map(normalize) } }
function cancel() { showEditor.value = false; editing.value = null }
function addField() { form.value.columns.push(emptyField()) }
function removeField(index: number) { if (form.value.columns.length === 1) { error.value = '模板至少保留一个表头字段'; return }; form.value.columns.splice(index, 1) }
async function save() {
  if (!form.value.name.trim()) { error.value = '模板名称不能为空'; return }
  const columns = form.value.columns.map(({ optionsText, ...field }) => ({ ...field, label: field.label.trim(), defaultValue: field.defaultValue || undefined, pattern: field.pattern || undefined, options: optionsText.split(',').map(item => item.trim()).filter(Boolean), maxLength: field.maxLength || undefined, minValue: field.minValue || undefined, maxValue: field.maxValue || undefined, scale: field.scale ?? undefined }))
  if (columns.some(field => !field.label)) { error.value = '请填写每个字段名称'; return }
  if (new Set(columns.map(field => field.label)).size !== columns.length) { error.value = '字段表头不能重复'; return }
  if (columns.some(field => (field.type === 'select' || field.type === 'multiselect') && !field.options.length)) { error.value = '下拉字段必须填写选项'; return }
  error.value = ''; message.value = ''
  try { const data = { name: form.value.name.trim(), description: form.value.description.trim(), status: form.value.status, columns }; if (editing.value) await updateTemplate(editing.value.id, data); else await createTemplate(data); message.value = editing.value ? '模板已保存并生成新版本' : '模板已保存'; cancel(); await load() } catch (e) { error.value = toMessage(e) }
}
async function remove(item: Template) { if (!window.confirm(`确认删除模板“${item.name}”吗？删除后将清空该模板的所有填报数据，此操作不可恢复。`)) return; try { await deleteTemplate(item.id); message.value = '模板及其关联填报数据已删除'; await load() } catch (e) { error.value = toMessage(e) } }
async function download(item: Template) { try { await downloadTemplate(item.id, item.name) } catch (e) { error.value = toMessage(e) } }
async function downloadImportSample() { try { await downloadTemplateImportSample() } catch (e) { error.value = toMessage(e) } }
async function upload(item: Template, event: Event) { const file = (event.target as HTMLInputElement).files?.[0]; if (!file) return; try { await uploadTemplateFile(item.id, file); message.value = '表头字段已更新并生成新版本'; await load() } catch (e) { error.value = toMessage(e) }; (event.target as HTMLInputElement).value = '' }
async function chooseImportFile(event: Event) { importFile.value = (event.target as HTMLInputElement).files?.[0] || null; importSheets.value = []; if (!importFile.value) return; importing.value = true; try { const result = await previewTemplateImport(importFile.value); importSheets.value = result.sheets.map(sheet => ({ ...sheet, templateName: '' })) } catch (e) { error.value = toMessage(e) } finally { importing.value = false } }
async function confirmImport() { if (!importFile.value || !importSheets.value.length || importSheets.value.some(sheet => !sheet.valid || !sheet.templateName.trim())) { error.value = '请确认表头校验通过，并填写每个工作表的模板名称'; return }; importing.value = true; try { const created = await confirmTemplateImport(importFile.value, importSheets.value.map(sheet => sheet.templateName.trim())); message.value = `已新增 ${created.length} 个模板`; importSheets.value = []; await load() } catch (e) { error.value = toMessage(e) } finally { importing.value = false } }
onMounted(load)
</script>

<template>
  <section>
    <div class="page-heading"><div><h1>模板维护</h1><p>模板保存后产生新版本，已发布任务和历史填报继续使用原版本。</p></div><button class="primary" @click="openCreate">新建模板</button></div>
    <div v-if="message" class="notice success">{{ message }}</div><div v-if="error" class="notice error">{{ error }}</div>
    <div class="editor template-import"><div class="field-editor-heading"><div><h2>从 Excel 批量新增模板</h2><p class="hint">每个工作表生成一个模板，仅允许表头，不允许包含数据。</p></div><button type="button" class="secondary" @click="downloadImportSample">下载导入样例</button></div><input type="file" accept=".xlsx,.xls" @change="chooseImportFile" /><div v-if="importSheets.length" class="sheet-preview"><table><thead><tr><th>顺序</th><th>工作表</th><th>校验</th><th>模板名称</th></tr></thead><tbody><tr v-for="sheet in importSheets" :key="sheet.sheetIndex"><td>{{ sheet.sheetOrder + 1 }}</td><td>{{ sheet.sheetName }}</td><td :class="sheet.valid ? 'valid-text' : 'invalid-text'">{{ sheet.valid ? '通过' : sheet.message }}</td><td><input v-model.trim="sheet.templateName" :disabled="!sheet.valid" /></td></tr></tbody></table><button class="primary" :disabled="importing" @click="confirmImport">确认新增模板</button></div></div>
    <form v-if="showEditor" class="editor" @submit.prevent="save"><h2>{{ editing ? '编辑模板（将生成新版本）' : '新建模板' }}</h2><div class="form-grid"><label>模板名称<input v-model.trim="form.name" maxlength="100" /></label><label>生命周期<select v-model="form.status"><option value="DRAFT">草稿</option><option value="VALIDATING">校验中</option><option value="PUBLISHED">已发布</option><option value="IN_USE">使用中</option><option value="DISABLED">已停用</option></select></label><label>模板说明<input v-model.trim="form.description" maxlength="200" /></label></div><div class="field-editor"><div class="field-editor-heading"><h3>字段配置</h3><button type="button" class="secondary" @click="addField">新增字段</button></div><div class="table-wrap"><table class="manual-table"><thead><tr><th>字段</th><th>类型</th><th>必填</th><th>默认值</th><th>长度</th><th>最小值</th><th>最大值</th><th>小数位</th><th>下拉选项（逗号分隔）</th><th>正则</th><th>属性</th><th>操作</th></tr></thead><tbody><tr v-for="(field, index) in form.columns" :key="field.key"><td><input v-model.trim="field.label" placeholder="字段名称" /></td><td><select v-model="field.type"><option value="text">文本</option><option value="textarea">多行文本</option><option value="number">数字</option><option value="money">金额</option><option value="date">日期</option><option value="month">月份</option><option value="year">年份</option><option value="select">下拉</option><option value="multiselect">多选</option><option value="attachment">附件</option></select></td><td><input v-model="field.required" type="checkbox" /></td><td><input v-model.trim="field.defaultValue" /></td><td><input v-model.number="field.maxLength" type="number" min="1" /></td><td><input v-model="field.minValue" type="number" /></td><td><input v-model="field.maxValue" type="number" /></td><td><input v-model.number="field.scale" type="number" min="0" max="8" /></td><td><input v-model.trim="field.optionsText" :disabled="field.type !== 'select' && field.type !== 'multiselect'" /></td><td><input v-model.trim="field.pattern" /></td><td><div class="field-properties"><label class="checkbox-label"><input v-model="field.uniqueValue" type="checkbox" />唯一</label><label class="checkbox-label"><input v-model="field.searchable" type="checkbox" />查</label><label class="checkbox-label"><input v-model="field.aggregatable" type="checkbox" />汇</label><label class="checkbox-label"><input v-model="field.listVisible" type="checkbox" />列</label><label class="checkbox-label"><input v-model="field.frozen" type="checkbox" />冻</label><label class="checkbox-label"><input v-model="field.importable" type="checkbox" />导</label></div></td><td><button type="button" class="danger-button" @click="removeField(index)">删除</button></td></tr></tbody></table></div></div><div class="actions"><button class="primary">保存</button><button type="button" class="secondary" @click="cancel">取消</button></div></form>
    <div class="table-wrap"><table><thead><tr><th>模板名称</th><th>状态</th><th>当前版本</th><th>说明</th><th>模板文件</th><th class="actions-cell">操作</th></tr></thead><tbody><tr v-if="loading"><td colspan="6" class="muted">加载中...</td></tr><tr v-else-if="!templates.length"><td colspan="6" class="muted">暂无模板。</td></tr><tr v-for="item in templates" :key="item.id"><td>{{ item.name }}</td><td>{{ item.status || '-' }}</td><td>V{{ item.currentVersionNo || '-' }}</td><td>{{ item.description || '-' }}</td><td><button class="text-button" @click="download(item)">下载模板文件</button></td><td class="actions-cell"><button class="text-button" @click="openEdit(item)">编辑</button><label class="text-button upload-label">导入表头<input type="file" accept=".xlsx,.xls" @change="upload(item, $event)" /></label><button class="danger-button" @click="remove(item)">删除</button></td></tr></tbody></table></div>
  </section>
</template>
